// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnlqxeaegbtzdfmzooze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubHF4ZWFlZ2J0emRmbXpvb3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODkxNjksImV4cCI6MjA2NTA2NTE2OX0.wAE4K8oLaLr_PgedP_S8uP2x72RCxv5HNApdH7SKPcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);